# Generated by Django 2.2.5 on 2020-04-07 19:35

import admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_like', models.IntegerField(blank=True, default=0, null=True)),
                ('is_show', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(max_length=64)),
                ('img', models.TextField(default=None, max_length=100)),
                ('content', models.TextField()),
                ('comment_number', models.IntegerField(blank=True, default=0, null=True)),
                ('read_number', models.IntegerField(blank=True, default=0, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mb_article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('liked_number', models.IntegerField(blank=True, default=0, null=True)),
                ('reply_count', models.IntegerField(blank=True, default=0, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.Article')),
            ],
            options={
                'db_table': 'mb_comment',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_name', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mb_link',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright_info', models.CharField(blank=True, max_length=255, null=True)),
                ('record_number', models.CharField(blank=True, max_length=255, null=True)),
                ('statistic_code', models.TextField(blank=True, max_length=1000, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mb_site',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to=admin.models.image_upload_to)),
                ('title', models.CharField(max_length=100)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mb_slide',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_img', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=86)),
                ('login_power', models.IntegerField()),
                ('login_state', models.IntegerField()),
                ('user_authority', models.IntegerField()),
                ('mobile_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(blank=True, null=True)),
                ('person_intro', models.TextField(blank=True, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mb_user',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_like', models.IntegerField(blank=True, null=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.Article')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.Comment')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.User')),
            ],
            options={
                'db_table': 'mb_like',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to='admin.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='admin.User'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_parent', models.IntegerField()),
                ('category_name', models.CharField(max_length=32)),
                ('gmt_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Category')),
            ],
            options={
                'db_table': 'mb_category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin.User'),
        ),
    ]
